name: Reusable

on:
  workflow_call:
    inputs:
      alpine:
        required: true
        type: string
      arch:
        required: true
        type: string

jobs:
  example:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Alpine Linux shell
        uses: jirutka/setup-alpine@v1
        with:
          branch: v${{ inputs.alpine }}
          arch: ${{ inputs.arch }}
      - name: Check
        run: uname -a && cat /etc/os-release
        shell: alpine.sh {0}