name: Test

on: 
  push:
    branches:
      - draft
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Alpine ${{ matrix.alpine }} ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - alpine: "3.23"
            arch: x86_64
          - alpine: "3.24"
            arch: x86_64
          - alpine: "3.23"
            arch: aarch64
          - alpine: "3.24"
            arch: armhf
    uses:
      ./.github/workflows/_build.yml
    with:
      alpine: ${{ matrix.alpine }}
      arch: ${{ matrix.arch }}
