name: Publish

on:
  push:
    branches:
      - draft

permissions:
  contents: write

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: ivanvc/abuild-releaser-action@main
#         with:
#           author: James Kelly <jamesdkelly88@outlook.com>
#           rsa_public_key: ${{ secrets.RSA_PUBLIC_KEY }}
#           rsa_private_key: ${{ secrets.RSA_PRIVATE_KEY }}
#           generate_index_pages: true
#           # generate_single_index_page: false
#           # alpine_branch: v3.23

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  

      - name: Setup Alpine Linux v3.23
        uses: jirutka/setup-alpine@v1
        with:
          branch: v3.23

      - name: Get OS Version
        run: cat /etc/os-release
        shell: alpine.sh {0}

      - name: Install abuild
        run: apk add alpine-sdk
        shell: alpine.sh --root {0}

      - name: Test
        run: echo $HOME
        shell: alpine.sh --root {0}

      - name: Add runner user to abuild group
        run: addgroup runner abuild
        shell: alpine.sh --root {0}

      - name: Store RSA Keys
        run: |
          echo $HOME
          echo "$RSA_PRIVATE_KEY" > "$HOME/$GITHUB_REPOSITORY_OWNER.rsa"
          echo "$RSA_PUBLIC_KEY" > "$HOME/$GITHUB_REPOSITORY_OWNER.rsa.pub"
          ls -al $HOME

          cp "$HOME/$GITHUB_REPOSITORY_OWNER.rsa.pub" /etc/apk/keys
          ls -al /etc/apk/keys
        shell: alpine.sh {0}
        env:
          RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
          RSA_PUBLIC_KEY: ${{ secrets.RSA_PUBLIC_KEY }}

      # - name: Test abuild
      #   run: abuild -V
      #   shell: alpine.sh {0}